version: '3.8'
services:
  building:
    build:
      context: ./bulding
      dockerfile: Dockerfile
    volumes: 
      - type: volume
        source: data
        target: /data
    command: cp /home/boxfuse-sample-java-war-hello/target/hello-1.0.war /data

  web:
    build:
      context: ./prod
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - data:/usr/local/tomcat/webapps/

volumes:
  data: